// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexScssNamespace {
  export interface IIndexScss {
    flex: string;
    navs: string;
    'some-style': string;
    test: string;
  }
}

declare const IndexScssModule: IndexScssNamespace.IIndexScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexScssNamespace.IIndexScss;
};

export = IndexScssModule;
